WetMarketOnline/Controllers/MstAdminController.cs
using EWM.HelperClass;
using EWM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EWM.Controllers
{
    public class MstAdminController : Controller
    {
        private static log4net.ILog Log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        //? MstAdmin Home Page
        public ActionResult MstAdmin()
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Admin")) { return RedirectToAction("Login", "Account"); }

            //ViewBag.Message = "Placeholder Admin Page";
            return View();
        }

        //? Order List page
        public ActionResult OrderList_Admin()
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Admin")) { return RedirectToAction("Login", "Account"); }
            return View();
        }

        public ActionResult OrderCard_AdminPartial(string status = "")
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Admin")) { return RedirectToAction("Login", "Account"); }

            List<TxnOrderHdr> orderList = TxnOrderHdr.GetAllOrders(status);
            orderList = orderList.OrderByDescending(l => l.UpdatedDate).ToList();
            return PartialView(orderList);
        }


        //? Order Tracking page
        public ActionResult OrderTracking_Admin(string orderHdrId)
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Admin")) { return RedirectToAction("Login", "Account"); }

            TxnOrderHdr hdr = TxnOrderHdr.GetTxnOrderHdr(orderHdrId);
            hdr.SetOrderDetails(TxnOrderDtl.GetCompleteOrderDetails(orderHdrId));

            return View(hdr);
        }


        //? AJAX - Update Order Status
        public ActionResult UpdateOrderStatus(string status, string orderHdrId)
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Admin")) { return RedirectToAction("Login", "Account"); }
            MstAdmin user = (MstAdmin)Session["Account"];

            TxnOrderHdr order = TxnOrderHdr.GetTxnOrderHdr(orderHdrId);
            order.Status = status;
            order.UpdateTxnOrderHdr(user.Username);

            return Json("Ok");
        }

    }
}

WetMarketOnline/Controllers/MstCategoryController.cs
using EWM.HelperClass;
using EWM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EWM.Controllers
{
    public class MstCategoryController : Controller
    {

        //? MstAdmin Manage Category Page
        public ActionResult ManageCategory()
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Admin")) { return RedirectToAction("Login", "Account"); }

            ViewData["MaxCat"] = MstCategory.GetMaxCat();
            ViewBag.Error = TempData["Error"];
            return View();
        }

        // GET: MstCategory/Details/5
        public ActionResult Details(string id, string mode, int catLevel = 1)
        {

            MstCategory catSearch = new MstCategory();
            catSearch.CatLevel = catLevel - 1;
            List<MstCategory> parentList = catSearch.SelectMstCategory("All");
            List<SelectListItem> selectionList = new List<SelectListItem>();

            foreach (var item in parentList)
            {
                SelectListItem selectionItem = new SelectListItem();
                selectionItem.Text = item.CategoryCode;
                selectionItem.Value = item.CategoryId;
                selectionList.Add(selectionItem);
            }

            ViewData["ParentList"] = selectionList;
            ViewData["PageMode"] = mode;

            if (mode == "New")
            {
                return View("MstCategory_Details", new MstCategory());
            }
            else
            {
                MstCategory categoryData = MstCategory.GetMstCategory(id);
                if (catLevel > 1)
                {
                    MstCategory parent = MstCategory.GetMstCategory(categoryData.ParentCatId);
                    categoryData.ParentCatId = parent.CategoryId;
                }
                return View("MstCategory_Details", categoryData);
            }
        }

        [HttpPost]
        public ActionResult UpdateMstCategory(MstCategory formData, string mode)
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Admin")) { return RedirectToAction("Login", "Account"); }
            MstAdmin member = (MstAdmin)Session["Account"];

            int rowsAffected = -1;

            if (mode == "New")
            {
                rowsAffected = formData.CreateMstCategory(member.Username);
            }
            else if (mode == "Edit")
            {
                MstCategory oriData = MstCategory.GetMstCategory(formData.CategoryId);
                oriData.CategoryCode = formData.CategoryCode;
                oriData.CategoryDesc = formData.CategoryDesc;
                oriData.CatLevel = formData.CatLevel;
                oriData.ParentCatId = formData.ParentCatId;
                oriData.Status = formData.Status;

                rowsAffected = oriData.UpdateMstCategory(member.Username);
            }

            if (rowsAffected == 1)
            {
                return RedirectToAction("ManageCategory");
            }
            else
            {
                ViewBag.Error = "Error processing request. Please try again";
                ViewData["PageMode"] = mode;
                return View("MstCategory_Details", formData);
            }

        }

        /// GET: MstCategory/Delete/5
        public ActionResult Delete(string id)
        {
            MstCategory deleteCat = MstCategory.GetMstCategory(id);
            List<MstCategory> checkChildren = MstCategory.GetCategoryDescendents(deleteCat.CatLevel.GetValueOrDefault(), deleteCat.CategoryId);

            if (checkChildren.Count > 0)
            {
                TempData["Error"] = "This category has children. Unable to delete category.";
                return RedirectToAction("ManageCategory");
            }

            int rowsAffected = deleteCat.DeleteMstCategory();

            if (rowsAffected != 1)
            {
                TempData["Error"] = "Failed to delete the category. Please try again.";
            }
            return RedirectToAction("ManageCategory");
        }

        public ActionResult ManageCategory_Level(int catLevel = 1)
        {
            //MstCategory catSearch = new MstCategory();
            //catSearch.CatLevel = catLevel;
            //List<MstCategory> list = catSearch.SelectMstCategory("All");
            List<MstCategory> list = MstCategory.GetCategoryDescendents(catLevel);
            list = list.OrderBy(l => l.CategoryCode).ToList();
            return PartialView(list);

        }

        //? AJAX call for Parent Cat dropdown
        public ActionResult GetParentCat_Cb(int catLevel = 1, string parentCat = "")
        {
            MstCategory catSearch = new MstCategory();
            catSearch.CatLevel = catLevel - 1;
            List<MstCategory> parentList = catSearch.SelectMstCategory("All");
            List<SelectListItem> selectionList = new List<SelectListItem>();

            foreach (var item in parentList)
            {
                SelectListItem selectionItem = new SelectListItem();
                selectionItem.Text = item.CategoryCode;
                selectionItem.Value = item.CategoryId;
                selectionList.Add(selectionItem);
            }

            return Json(selectionList);
        }

        //? AJAX Check Categpry Code Validity
        public ActionResult ValidateCategory(string catCode, string catId)
        {
            MstCategory cat = new MstCategory();
            cat.CategoryCode = catCode;
            List<MstCategory> catList = cat.SelectMstCategory("All");

            if (catList.Count == 0 || (catList.Count == 1 && catList[0].CategoryId == catId))
            {
                return Json("Ok");
            }
            else
            {
                return Json("Category Code is in use!");
            }
        }

        //end class
    }
}

WetMarketOnline/Controllers/MstCustomerController.cs
using EWM.HelperClass;
using EWM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EWM.Controllers
{
    public class MstCustomerController : Controller
    {
        private static log4net.ILog Log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        // Customer Home page
        public ActionResult MstCustomer()
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Customer")) { return RedirectToAction("Login", "Account"); }

            return View();
        }

        // Customer Profile page
        public ActionResult CustomerProfile(string pageMode = "Details", string accessMode = "Customer", string customerId = "")
        {
            string profileId = "";
            if (accessMode == "Customer")
            {
                if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Customer")) { return RedirectToAction("Login", "Account"); }
                MstCustomer member = (MstCustomer)Session["Account"];
                profileId = member.CustomerId;
            }

            if (accessMode == "Admin")
            {
                if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Admin")) { return RedirectToAction("Login", "Account"); }
                profileId = customerId;
            }

            MstCustomer model = Models.MstCustomer.GetMstCustomer(profileId);
            ViewData["PageMode"] = pageMode;
            ViewData["AccessMode"] = accessMode;
            return View(model);
        }

        // EDIT: MstCustomer
        public ActionResult CustomerProfile_Edit(string pageMode = "Edit")
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Customer")) { return RedirectToAction("Login", "Account"); }

            MstCustomer member = (MstCustomer)Session["Account"];
            MstCustomer model = Models.MstCustomer.GetMstCustomer(member.CustomerId);

            ViewData["PageMode"] = pageMode;
            return View(model);
        }

        [HttpPost]
        public ActionResult SaveCustomerProfile(MstCustomer formData)
        {

            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Customer")) { return RedirectToAction("Login", "Account"); }
            MstCustomer member = (MstCustomer)Session["Account"];

            int rowsAffected = -1;

            MstCustomer customerData = EWM.Models.MstCustomer.GetMstCustomer(formData.CustomerId);
            customerData.Email = formData.Email;
            customerData.Address = formData.Address;
            customerData.Postcode = formData.Postcode;
            customerData.State = formData.State;
            customerData.Name = formData.Name;
            customerData.Username = formData.Username;


            rowsAffected = customerData.UpdateMstCustomer(member.Username);

            if (rowsAffected == 1)
            {
                return RedirectToAction("CustomerProfile");
            }
            else
            {
                ViewBag.Error = "Error processing request. Please try again";
                ViewData["PageMode"] = "Edit";
                return View("CustomerProfile_Edit", formData);
            }

        }

        //? Order List page
        public ActionResult OrderList()
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Customer")) { return RedirectToAction("Login", "Account"); }
            return View();
        }

        public ActionResult OrderCard_Partial(string status = "")
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Customer")) { return RedirectToAction("Login", "Account"); }
            MstCustomer user = (MstCustomer)Session["Account"];

            List<TxnOrderHdr> orderList = TxnOrderHdr.GetCustomerOrder(user.CustomerId, status);
            orderList = orderList.OrderByDescending(l => l.UpdatedDate).ToList();
            return PartialView(orderList);
        }


        //? Order Tracking page
        public ActionResult OrderTracking(string orderHdrId)
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Customer")) { return RedirectToAction("Login", "Account"); }
            MstCustomer user = (MstCustomer)Session["Account"];

            TxnOrderHdr hdr = TxnOrderHdr.GetTxnOrderHdr(orderHdrId);
            hdr.SetOrderDetails(TxnOrderDtl.GetCompleteOrderDetails(orderHdrId));

            return View(hdr);
        }

        //? AJAX Check Username Availability
        public ActionResult ValidateUsername(string username, string customerId)
        {
            MstCustomer customer = new MstCustomer();
            customer.Username = username;
            List<MstCustomer> customerList = customer.SelectMstCustomer("All");

            if (customerList.Count == 0 || (customerList.Count == 1 && customerList[0].CustomerId == customerId))
            {
                return Json("Ok");
            }
            else
            {
                return Json("Username is in use!");
            }
        }

        ////? Change Password popup
        //public ActionResult ChangePassword_Customer()
        //{
        //    return PartialView();
        //}

        //? Change customer password
        [HttpPost]
        public ActionResult ChangePassword(string password)
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Customer")) { return RedirectToAction("Login", "Account"); }
            MstCustomer user = (MstCustomer)Session["Account"];

            MstCustomer customer = Models.MstCustomer.GetMstCustomer(user.CustomerId);
            customer.Password = password;
            customer.UpdateMstCustomer();

            return RedirectToAction("CustomerProfile");
        }
    }
}

WetMarketOnline/Controllers/MstPromotionController.cs
using EWM.HelperClass;
using EWM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EWM.Controllers
{
    public class MstPromotionController : Controller
    {

        //? MstAdmin Manage Promotion Page
        public ActionResult ManagePromotion()
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Admin")) { return RedirectToAction("Login", "Account"); }

            List<MstPromotion> list = MstPromotion.SelectMstPromotion_All();
            return View(list);
        }

        // GET: MstPromotion/Details/5
        public ActionResult Details(string id, string mode)
        {

            ViewData["PageMode"] = mode;
            if (mode == "New")
            {
                return View("MstPromotion_Details", new MstPromotion());
            }
            else
            {
                MstPromotion slider = MstPromotion.GetMstPromotion(id);
                return View("MstPromotion_Details", slider);
            }
        }

        [HttpPost]
        public ActionResult UpdateMstPromotion(MstPromotion formData, string mode)
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Admin")) { return RedirectToAction("Login", "Account"); }
            MstAdmin member = (MstAdmin)Session["Account"];

            int rowsAffected = -1;

            if (mode == "New")
            {
                rowsAffected = formData.CreateMstPromotion(member.Username);
            }
            else if (mode == "Edit")
            {
                MstPromotion oriData = MstPromotion.GetMstPromotion(formData.PromotionId);
                oriData.PromotionCode = formData.PromotionCode;
                oriData.PromotionDesc = formData.PromotionDesc;
                oriData.StartDate = formData.StartDate;
                oriData.EndDate = formData.EndDate;
                oriData.Status = formData.Status;
                oriData.Amount = formData.Amount;

                rowsAffected = oriData.UpdateMstPromotion(member.Username);
            }

            if (rowsAffected == 1)
            {
                return RedirectToAction("ManagePromotion");
            }
            else
            {
                ViewBag.Error = "Error processing request. Please try again";
                ViewData["PageMode"] = mode;
                return View("MstPromotion_Details", formData);
            }

        }

        /// GET: MstPromotion/Delete/5
        public ActionResult Delete(string id)
        {
            MstPromotion promo = MstPromotion.GetMstPromotion(id);
            int rowsAffected = promo.DeleteMstPromotion();


            if (rowsAffected == 1)
            {
                return RedirectToAction("ManagePromotion");
            }
            else
            {
                ViewBag.Error = "Failed to delete the promotion. Please try again.";
                return View();
            }
        }

        //? AJAX Check Promotion Code Validity
        public ActionResult ValidatePromotion(string promoCode, string promoId)
        {
            MstPromotion promo = new MstPromotion();
            promo.PromotionCode = promoCode;
            List<MstPromotion> promoList = promo.SelectMstPromotion("All");
           
            if (promoList.Count == 0 || (promoList.Count == 1 && promoList[0].PromotionId == promoId))
            {
                return Json("Ok");
            } else
            {
                return Json("Promotion Code is in use!");
            }
        }

    }
}

WetMarketOnline/Views/MstAdmin/MstAdmin.cshtml
@{
    ViewBag.Title = "Admin Home";
}

<h2>Welcome Back, Admin</h2>

<div class="row row-cols-3 my-5 justify-content-center text-center">
    <div class=" col card text-black me-3" style="max-width: 250px;">
        <a class="custom-link" href='@Url.Action("ManageHomeSlider", "MstHomeSlider")'>
            <img src="~/Content/Img/Admin_ManageHome.png" class="card-img" alt="Manage Home Page Icon">
            <div class="card-body">
                <h5 class="card-title">Manage Home Slider</h5>
            </div>
        </a>
    </div>

    <div class=" col card text-black me-3" style="max-width: 250px;">
        <a class="custom-link" href='@Url.Action("ManagePromotion", "MstPromotion")'>
            <img src="~/Content/Img/Admin_ManagePromotion.jpg" class="card-img" alt="Manage Promotion Icon">
            <div class="card-body">
                <h5 class="card-title">Manage Promotion</h5>
            </div>
        </a>
    </div>

    <div class=" col card text-black me-3" style="max-width: 250px;">
        <a class="custom-link" href='@Url.Action("ManageCategory", "MstCategory")'>
            <img src="~/Content/Img/Admin_ManageCategory.png" class="card-img" alt="Manage Categories Icon">
            <div class="card-body">
                <h5 class="card-title">Manage Categories</h5>
            </div>
        </a>
    </div>

    <div class=" col card text-black me-3" style="max-width: 250px;">
        <a class="custom-link" href='@Url.Action("OrderList_Admin")'>
            @*<img src="~/Content/Img/Admin_ManageHome.png" class="card-img" alt="Manage Products Icon">*@
            <i class="bi bi-bag-fill" style="font-size: 8rem; color: black;"></i>
            <div class="card-body">
                <h5 class="card-title">View Orders</h5>
            </div>
        </a>
    </div>
</div>

WetMarketOnline/Views/MstAdmin/OrderCard_AdminPartial.cshtml
@using EWM.Models;
@model List<TxnOrderHdr>
@{
    if (Model.Count == 0)
    {
        <h4><strong>No orders.</strong></h4>
    }

    foreach (var item in Model)
    {
        string iconClass = (item.Status == "Delivered") ? "bi-box2" : (item.Status == "Picked Up") ? "bi-person-fill" : (item.Status == "On the Way") ? "bi-truck" : "bi-check-lg";
        decimal price = Math.Round(item.TotalPrice.Value, 2);

        <div class="card mb-4">
            <a id="orderLink" href='@Url.Action("OrderTracking_Admin", new { orderHdrId = item.OrderHdrId })'>
                <div class="card-header bg-secondary bg-gradient text-white">
                    Order Id: #@item.OrderHdrId
                </div>
            </a>
            <div class="row g-0">
                <div class="col-md-3 justify-content-center text-center m-auto">
                    <a href='@Url.Action("OrderTracking_Admin", new { orderHdrId = item.OrderHdrId })' class="text-decoration-none text-reset">
                        <span class="px-3 border border-1 border-dark rounded-3" style="font-size:5rem;">
                            <i class="bi @iconClass"></i>
                        </span>
                    </a>
                </div>
                <div class="col-md-9">
                    <div class="card-body">
                        <a id="customerProfileLink" href='@Url.Action("CustomerProfile", "MstCustomer", new {  pageMode = "Details", accessMode = "Admin", customerId = item.CustomerId })' class="">
                            <h5 class="card-title">Customer: @item.GetCustomerName()</h5>
                        </a>
                        <p class="card-text">Order Date: @item.OrderDate.ToString("dd-MM-yyyy")</p>
                        <p class="card-text">Status: @item.Status</p>
                        <p class="card-text">Total: RM @price</p>
                        <p class="card-text"><small class="text-muted">@item.GetOrderDetails().Count item(s)</small></p>
                    </div>
                </div>
            </div>
        </div>

    }
}

WetMarketOnline/Views/MstAdmin/OrderList_Admin.cshtml
@{
    ViewBag.Title = "Order List";
}

<script type="text/javascript">
    $(document).ready(() => {
        $("#orderFilter").change(e => {
            filterOrders();
        })
    });

    function filterOrders() {
        var orderStatus = $("#orderFilter").val();

         $.ajax({
                type: "POST",
                url: '@Url.Action("OrderCard_AdminPartial")',
                data: {
                    status: orderStatus
                },
                dataType: "html",
             success: function (result) {
                 $("#OrderCard_Partial").html(result);                 
                }
            });
    }
</script>

<h2>Orders</h2>
<hr />
@* Filter *@
<div class="mb-5">

<h6 class="title">Filter Order Status:</h6>
<select id="orderFilter" class="form-select" aria-label="Select an order filter">
    <option selected>All</option>
    <option value="Order Confirmed">Order Confirmed</option>
    <option value="Picked Up">Picked Up</option>
    <option value="On the Way">On the Way</option>
    <option value="Delivered">Delivered</option>
</select>
</div>

@* Order List *@
<div id="OrderCard_Partial">
    @{Html.RenderAction("OrderCard_AdminPartial");    }
</div>

WetMarketOnline/Views/MstAdmin/OrderTracking_Admin.cshtml
@using EWM.Models;
@model TxnOrderHdr

@{
    ViewBag.Title = "Order Tracking";


    string directory = EWM.HelperClass.GeneralBLL.FileDirectory;

    string confirmStatus = "active";
    string pickUpStatus = "";
    string shippingStatus = "";
    string deliveryStatus = "";
    string statusUpdate = "Picked Up by Courier";
    string newStatus = "Picked Up";
    string statusUpdateBtn = "outline-dark";
    string statusIcon = "person-fill";

    if (Model.Status == "Picked Up")
    {
        pickUpStatus = "active";
        statusUpdate = "Order being Delivered";
        newStatus = "On the Way";
        statusIcon = "truck";
    }

    if (Model.Status == "On the Way")
    {
        pickUpStatus = "active";
        shippingStatus = "active";
        statusUpdate = "Order Delivered";
        newStatus = "Delivered";
        statusIcon = "box2";
    }

    if (Model.Status == "Delivered")
    {
        pickUpStatus = "active";
        shippingStatus = "active";
        deliveryStatus = "active";
        statusUpdate = "Order Delivered";
        statusIcon = "box2";
        statusUpdateBtn = "secondary disabled";
    }
    //alter table txn_order_hdr alter column status varchar(100)

}

<script type="text/javascript">
  $(document).ready(() => {
        $("#btnStatusUpdate").click(e => {
            updateStatus();
        })
    });

    function updateStatus() {

         $.ajax({
                type: "POST",
                url: '@Url.Action("UpdateOrderStatus")',
                data: {
                    status: $("#orderStatus").val(),
                    orderHdrId: "@Model.OrderHdrId"
                },
                dataType: "json",
             success: function (result) {
                 if (result != "Ok") { console.log(result); }
        location.reload();
                }
            });
                 //$('#orderTracker').load('#orderTracker #orderTracker');
    }

</script>

@*<h2>OrderTracking</h2>*@

<div class="container mb-4">
    <article class="card">
        <div class="card-body">
            <h6>Order ID: #@Model.OrderHdrId</h6>
            <article class="card">
                <div class="card-body row">
                    @*<div class="col"><strong>Estimated Delivery time:</strong> <br>29 nov 2019 </div>*@
                    <div class="col"> <strong>Shipping By:</strong> <br> EWM Courier | <i class="bi bi-phone"></i> +60-123 5134 </div>
                    <div class="col"> <strong>Status:</strong> <br> @Model.Status</div>
                    @*<div class="col"> <strong>Tracking #:</strong> <br> BD045903594059 </div>*@
                </div>
            </article>
            <hr />
            <div id="orderTracker" class="track">
                <div class="step @confirmStatus"> <span class="icon"> <i class="bi bi-check-lg"></i></span> <span class="text">Order confirmed</span> </div>
                <div class="step @pickUpStatus"> <span class="icon"> <i class="bi bi-person-fill"></i> </span> <span class="text"> Picked by courier</span> </div>
                <div class="step @shippingStatus"> <span class="icon"> <i class="bi bi-truck"></i> </span> <span class="text"> On the way </span> </div>
                <div class="step @deliveryStatus"> <span class="icon"> <i class="bi bi-box2-fill"></i> </span> <span class="text">Delivered</span> </div>
            </div>
            <div class="text-end pt-5">
                <span>
                    <strong class="me-2">Update Order Status:</strong>
                </span>
                <button id="btnStatusUpdate" class="btn btn-@statusUpdateBtn"><i class="bi bi-@statusIcon pe-3"></i>@statusUpdate</button>
                <input type="hidden" id="orderStatus" value="@newStatus" />
            </div>

            <hr />
            <ul class="track-item row">
                @{
                    foreach (var item in Model.GetOrderDetails())
                    {
                        MstProduct orderItem = item.GetOrderItem();
                        MstProductImage img = (orderItem.GetImageList().Count <= 0) ? null : orderItem.GetImageList().OrderBy(l => l.ImageOrder).ToList()[0];
                        string imgLink = (img != null) ? String.Concat(directory, img.FileLocation) : "";
                        string desc = (img != null) ? img.ImageDesc : "Image not found";
                        decimal price = Decimal.Round(orderItem.Price.Value, 2);

                        <li class="col-md-4">
                            <figure class="itemside mb-3">
                                <div class="aside"><img src="@imgLink" alt="@desc" class="img-sm border"></div>
                                <figcaption class="info align-self-center">
                                    <p class="title">@orderItem.ProductName</p>
                                    <p class="title text-muted">RM @price | @item.Quantity unit(s)</p>
                                    <small class="text-muted">@orderItem.GetMerchantName()</small>
                                </figcaption>
                            </figure>
                        </li>
                    }
                }
            </ul>
            <hr>
            <div class="card-body row">
                @*<div class="col"><strong>Estimated Delivery time:</strong> <br>29 nov 2019 </div>*@
                <div class="col"> <strong>Shipping Fee:</strong> <br> RM 5.00</div>
                <div class="col"> <strong>Promotion:</strong> <br> @Model.GetPromotionCode() | RM @Math.Round(Model.Discount.Value, 2) </div>
                <div class="col"> <strong>Order Total:</strong> <br> RM @Math.Round(Model.TotalPrice.Value, 2)</div>

                @*<div class="col"> <strong>Tracking #:</strong> <br> BD045903594059 </div>*@
            </div>
            <hr>
            <a href='@Url.Action("OrderList_Admin")' class="btn btn-warning mt-5" data-abc="true"> <i class="bi bi-chevron-left"></i> Back to orders</a>
        </div>
    </article>
</div>