WetMarketOnline/Models/MstHomeSlider.cs
using EWM.HelperClass;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlClient;

namespace EWM.Models
{
    public class MstHomeSlider
    {
        private static log4net.ILog Log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        public static string ObjectName = typeof(MstHomeSlider).AssemblyQualifiedName;
        public static string ListName = typeof(List<MstHomeSlider>).AssemblyQualifiedName;
        //public static string FileDirectory = System.Configuration.ConfigurationManager.AppSettings["UploadDirectoryForPhoto"];

        public string SliderPhotoId { get; set; }
        [Display(Name = "File Location")]
        public string FileLocation { get; set; }
        [Display(Name = "Description")]
        public string ImageDesc { get; set; }
        [Display(Name = "File Name")]
        public string Filename { get; set; }
        [Display(Name = "File Extension")]
        public string ExtensionType { get; set; }
        public string Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        [Display(Name = "Last Changed")]
        public DateTime UpdatedDate { get; set; }
        [Display(Name = "Updated By")]
        public string UpdatedBy { get; set; }


        private string OriSliderPhotoId { get; set; }
        private string OriFileLocation { get; set; }
        private string OriImageDesc { get; set; }
        private string OriFilename { get; set; }
        private string OriExtensionType { get; set; }
        private string OriStatus { get; set; }
        private DateTime OriCreatedDate { get; set; }
        private string OriCreatedBy { get; set; }
        private DateTime OriUpdatedDate { get; set; }
        private string OriUpdatedBy { get; set; }

        // Default Constructor
        public MstHomeSlider() { }

        // Retrieve from Db based on PK
        public static MstHomeSlider GetMstHomeSlider(string imgId)
        {
            MstHomeSlider img = new MstHomeSlider();
            img.SliderPhotoId = imgId;

            SqlCommand cmd = DatabaseManager.ConstructSqlCommand(ObjectName, img, filterType: "All");
            List<MstHomeSlider> imgList = (List<MstHomeSlider>)DatabaseManager.ExecuteQueryCommand_Object(cmd, ObjectName, ListName);

            if (imgList.Count == 1)
            {
                return imgList[0];
            }
            return null;
        }

        #region Getter/Setter

        public string GetOriFileName()
        {
            return OriFilename;
        }

        public string GetOriFileLocation()
        {
            return OriFileLocation;
        }

        #endregion

        #region Methods

        //? Insert new record
        public int CreateMstHomeSlider(string userName = "")
        {
            this.SliderPhotoId = Guid.NewGuid().ToString();
            this.Status = "Active";
            this.CreatedDate = DateTime.Now;
            this.UpdatedDate = DateTime.Now;
            this.CreatedBy = userName;
            this.UpdatedBy = userName;

            SqlCommand cmd = DatabaseManager.ConstructSqlCommand(ObjectName, this, "Insert");
            int rowsAffected = DatabaseManager.ExecuteQueryCommand_RowsAffected(cmd);

            return rowsAffected;
        }

        //? Update existing record
        public int UpdateMstHomeSlider(string userName = "")
        {
            this.UpdatedDate = DateTime.Now;
            this.UpdatedBy = userName;

            SqlCommand cmd = DatabaseManager.ConstructSqlCommand(ObjectName, this, "Update");
            int rowsAffected = DatabaseManager.ExecuteQueryCommand_RowsAffected(cmd);

            return rowsAffected;
        }

        //? Delete existing record
        public int DeleteMstHomeSlider()
        {
            SqlCommand cmd = DatabaseManager.ConstructSqlCommand(ObjectName, this, "Delete");
            int rowsAffected = DatabaseManager.ExecuteQueryCommand_RowsAffected(cmd);

            return rowsAffected;
        }

        //? Select from database based on value
        public List<MstHomeSlider> SelectMstHomeSlider(string filterType = "Column")
        {
            SqlCommand cmd = DatabaseManager.ConstructSqlCommand(ObjectName, this, "Select", filterType);
            List<MstHomeSlider> data = (List<MstHomeSlider>)DatabaseManager.ExecuteQueryCommand_Object(cmd, ObjectName, ListName);

            if (data == null)
            {
                data = new List<MstHomeSlider>();
            }
            return data;
        }

        //? Runs a Select statement and returns the number of rows found
        public int CheckMstHomeSlider()
        {
            SqlCommand cmd = DatabaseManager.ConstructSqlCommand(ObjectName, this, "Select", filterType: "All");
            int data = DatabaseManager.ExecuteQueryCommand_RowsAffected(cmd, true);

            return data;
        }

        //? Select all records from database
        public static List<MstHomeSlider> SelectMstHomeSlider_All()
        {
            SqlCommand cmd = DatabaseManager.ConstructSqlCommand(ObjectName, null, "SelectAll");
            List<MstHomeSlider> data = (List<MstHomeSlider>)DatabaseManager.ExecuteQueryCommand_Object(cmd, ObjectName, ListName);

            if (data == null)
            {
                data = new List<MstHomeSlider>();
            }
            return data;
        }

        
        #endregion
        //end class
    }
}

WetMarketOnline/Controllers/MstHomeSliderController.cs
using EWM.HelperClass;
using EWM.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;



namespace EWM.Controllers
{
    public class MstHomeSliderController : Controller
    {
        //? MstAdmin Manage Home Slider Images Page
        public ActionResult ManageHomeSlider()
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Admin")) { return RedirectToAction("Login", "Account"); }

            List<MstHomeSlider> imgList = MstHomeSlider.SelectMstHomeSlider_All();

            return View(imgList);
        }

        // GET: MstHomeSlider/Details/5
        public ActionResult Details(string id, string mode)
        {

            ViewData["PageMode"] = mode;
            if (mode == "New")
            {
                return View("HomeSlider_ImageDetails", new MstHomeSlider());
            }
            else
            {
                MstHomeSlider slider = MstHomeSlider.GetMstHomeSlider(id);
                return View("HomeSlider_ImageDetails", slider);
            }
        }

        [HttpPost]
        //? Update/Add new MstHomeSlider record
        public ActionResult UpdateMstHomeSlider(MstHomeSlider formData, HttpPostedFileBase FormFileUpload, string mode)
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Admin")) { return RedirectToAction("Login", "Account"); }
            MstAdmin member = (MstAdmin)Session["Account"];
            string fileExtension = "";
            string filePath = "";
            int rowsAffected = -1;

            //Get absolute Upload path 
            string UploadPath = Server.MapPath(GeneralBLL.FileDirectory);

            // File Path Configuration
            if (FormFileUpload != null)
            {
                string fileName = formData.Filename;    
                fileExtension = Path.GetExtension(FormFileUpload.FileName);

                //Add Current Date To Attached File Name : Filename_20220226.png
                string completeFileName = fileName.Trim() + "_" + DateTime.Now.ToString("yyyyMMdd") + fileExtension;

                //Create relative path to store in server.  
                filePath = typeof(MstHomeSlider).Name + "/" + completeFileName;

                GeneralBLL.MapFilePath(string.Concat(UploadPath, typeof(MstHomeSlider).Name));

                //To copy and save file into server.  
                FormFileUpload.SaveAs(String.Concat(UploadPath, filePath));


                // Set to form data values
                formData.ExtensionType = fileExtension;
                formData.FileLocation = filePath;
            }

            if (mode == "Edit")
            {
                MstHomeSlider oriSlider = MstHomeSlider.GetMstHomeSlider(formData.SliderPhotoId);
                oriSlider.Filename = formData.Filename;
                oriSlider.Status = formData.Status;
                oriSlider.ImageDesc = formData.ImageDesc;

                oriSlider.FileLocation = formData.FileLocation;
                oriSlider.ExtensionType = formData.ExtensionType;

                if (FormFileUpload == null) //if no file was uploaded
                {
                    string newFilePath = formData.FileLocation.Replace(oriSlider.GetOriFileName(), formData.Filename);
                    System.IO.File.Move(string.Concat(UploadPath, formData.FileLocation), string.Concat(UploadPath, newFilePath));

                    oriSlider.FileLocation = newFilePath;
                }
                rowsAffected = oriSlider.UpdateMstHomeSlider(member.Username);
            }
            else if (mode == "New")
            {
                rowsAffected = formData.CreateMstHomeSlider(member.Username);
            }


            if (rowsAffected == 1)
            {
                return RedirectToAction("ManageHomeSlider");
            }
            else
            {
                ViewBag.Error = "Error processing request. Please try again";
                return View("HomeSlider_ImageDetails", formData);
        }

        }

        // GET: MstHomeSlider/Delete/5
        public ActionResult Delete(string id)
        {
            MstHomeSlider slider = MstHomeSlider.GetMstHomeSlider(id);
            int rowsAffected = slider.DeleteMstHomeSlider();

            string UploadPath = Server.MapPath(GeneralBLL.FileDirectory);
            System.IO.File.Delete(String.Concat(UploadPath, slider.FileLocation));

            if (rowsAffected == 1)
            {
                return RedirectToAction("ManageHomeSlider");
            }
            else
            {
                ViewBag.Error = "Failed to delete the image. Please try again.";
                return View();
            }
        }

        //end class
    }
}

WetMarketOnline/Views/MstHomeSlider/HomeSlider_ImageDetails.cshtml
@using EWM.Models;
@using EWM.HelperClass
@model EWM.Models.MstHomeSlider

@{
    ViewBag.Title = "EWM - Home Slider";

    string pageMode = (ViewData["PageMode"] == null) ? "Details" : ViewData["PageMode"].ToString();
    string directory = GeneralBLL.FileDirectory;
    string imgPath = Url.Content(string.Concat("~", directory, Model.FileLocation));
    string altText = string.IsNullOrEmpty(Model.ImageDesc) ? "<< No Image >>" : Model.ImageDesc;
}

<script type="text/javascript">
    $(document).ready(() => {
        $("#btnFile").click(e => {
            $("#FormFileUpload").click();
        });

        $("#FormFileUpload").change(
            function () {
                if ($(this).val() != "") {
                    $("#btnFile").addClass("btn-success");
                    $("#btnFile").removeClass("btn-primary");
                    $("#btnFile").text("File Uploaded");
                } else {
                    $("#btnFile").addClass("btn-primary");
                    $("#btnFile").removeClass("btn-success");
                    $("#btnFile").text("Upload File");
                }
            });

        $("#btnSubmit").click(e => {
            if (validateData()) {
                $("#HomeSliderForm").submit();
            } else {
                alert("Please fill in all required fields!");
            }
        })
    });

    function validateData() {
        if ($("#Filename").val() == "" || $("#Filename").val() == null) { return false; }
        if ($("#ImageDesc").val() == "" || $("#ImageDesc").val() == null) { return false; }
        if ($("#FormFileUpload").val() == "" || $("#FormFileUpload").val() == null) { return false; }
        return true;
    }

</script>

<h2>@Model.Filename</h2>
<div class="row justify-content-center">
    <div class="text-center mb-4" style="max-width: 500px">
        <img src="@imgPath" class="img-fluid rounded  d-block" alt="@altText">
    </div>
</div>

<div class="mb-5">
    <h4>@pageMode</h4>
    <p class="text-danger">@ViewBag.Error</p>
    <hr />

    @using (Html.BeginForm("UpdateMstHomeSlider", "MstHomeSlider", new { mode = pageMode }, FormMethod.Post, new { enctype = "multipart/form-data", @id = "HomeSliderForm" }))
    {
    <dl class="dl-horizontal">
        @Html.TextBoxFor(model => model.SliderPhotoId, new { @class = "d-none" })
        <dt>
            @Html.DisplayNameFor(model => model.Filename)
        </dt>

        <dd class="mb-4">
            @{
                if (pageMode == "Details")
                {
                    @Html.DisplayFor(model => model.Filename)
                }
                else
                {
                    @Html.TextBoxFor(model => model.Filename, new { @class = "form-control", @required = "true" })
                }
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageDesc)
        </dt>

        <dd class="mb-4">

            @{
                if (pageMode == "Details")
                {
                    @Html.DisplayFor(model => model.ImageDesc)
                }
                else
                {
                    @Html.TextBoxFor(model => model.ImageDesc, new { @class = "form-control", @required = "true" })
                }
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileLocation)
        </dt>

        <dd class="mb-4 text-break">
            @{
                if (pageMode == "Details")
                {
                    @Html.DisplayFor(model => model.FileLocation)
                }
                else
                {
                    @Html.TextBoxFor(model => model.FileLocation, new { @readonly = "true", @class="form-control" })
                    <div class="row-cols-sm-3 row-cols-lg-6 mt-sm-3">
                        <button id="btnFile" type="button" class="btn btn-primary end-0">Upload File</button>
                        <input class="form-control visually-hidden" type="file" id="FormFileUpload" name="FormFileUpload">

                    </div>
                }
            }
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.ExtensionType)
        </dt>

        <dd class="mb-4">
            @Html.DisplayFor(model => model.ExtensionType, new { @class = "form-label" })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd class="mb-4">
            @{
                if (pageMode == "Details")
                {
                    @Html.DisplayFor(model => model.Status)
                }
                else
                {
                    @Html.DropDownListFor(model => model.Status, new SelectList(Enum.GetValues(typeof(GeneralBLL.Status))), new { @class = "form-select" })
                }
            }
        </dd>

        @*@  <dt>
            Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd class="mb-4">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>

        <dd class="mb-4">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>

        <dd class="mb-4">
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>



        @*<dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>*@

        @*<dd class="mb-4">
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>*@

    </dl>
    }
</div>

<div class="d-grid gap-2 d-md-flex justify-content-md-end mb-5">

    <a href='@Url.Action("ManageHomeSlider")' class="btn btn-secondary me-3 px-4">Back</a>

    @{
        if (pageMode != "Details")
        {
            <button class="btn btn-success px-4" id="btnSubmit" type="button" form="HomeSliderForm">Submit</button>
        }
    }

</div>

@*<p>
        @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
        @Html.ActionLink("Back to List", "Index")
    </p>*@

WetMarketOnline/Views/MstHomeSlider/ManageHomeSlider.cshtml
@model IEnumerable<EWM.Models.MstHomeSlider>

@{
    ViewBag.Title = "Manage Home Slider";
}

<script type="text/javascript">


</script>

<h2>Manage Home Slider</h2>

<p class="text-danger">@ViewBag.Error</p>

<table class="table mb-5">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Filename)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageDesc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExtensionType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </th>
        <th colspan="3" class="text-center">@Html.ActionLink("Add New", "Details", new { mode = "New" })</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Filename)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImageDesc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExtensionType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedDate)
            </td>
            <td>
            <td>
                @Html.ActionLink("Edit", "Details", new { id = item.SliderPhotoId, mode = "Edit" }) |
                @Html.ActionLink("Details", "Details", new { id = item.SliderPhotoId, mode = "Details" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.SliderPhotoId }, new { onclick = "return confirm('Are you sure you wish to delete " + item.Filename + "?');" })

            </td>
        </tr>
    }

</table>