WetMarketOnline/Controllers/MstAdminController.cs
using EWM.HelperClass;
using EWM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EWM.Controllers
{
    public class MstAdminController : Controller
    {
        private static log4net.ILog Log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        //? MstAdmin Home Page
        public ActionResult MstAdmin()
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Admin")) { return RedirectToAction("Login", "Account"); }

            //ViewBag.Message = "Placeholder Admin Page";
            return View();
        }

        //? Order List page
        public ActionResult OrderList_Admin()
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Admin")) { return RedirectToAction("Login", "Account"); }
            return View();
        }

        public ActionResult OrderCard_AdminPartial(string status = "")
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Admin")) { return RedirectToAction("Login", "Account"); }

            List<TxnOrderHdr> orderList = TxnOrderHdr.GetAllOrders(status);
            orderList = orderList.OrderByDescending(l => l.UpdatedDate).ToList();
            return PartialView(orderList);
        }


        //? Order Tracking page
        public ActionResult OrderTracking_Admin(string orderHdrId)
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Admin")) { return RedirectToAction("Login", "Account"); }

            TxnOrderHdr hdr = TxnOrderHdr.GetTxnOrderHdr(orderHdrId);
            hdr.SetOrderDetails(TxnOrderDtl.GetCompleteOrderDetails(orderHdrId));

            return View(hdr);
        }


        //? AJAX - Update Order Status
        public ActionResult UpdateOrderStatus(string status, string orderHdrId)
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Admin")) { return RedirectToAction("Login", "Account"); }
            MstAdmin user = (MstAdmin)Session["Account"];

            TxnOrderHdr order = TxnOrderHdr.GetTxnOrderHdr(orderHdrId);
            order.Status = status;
            order.UpdateTxnOrderHdr(user.Username);

            return Json("Ok");
        }

    }
}

WetMarketOnline/Controllers/ProductController.cs
using EWM.HelperClass;
using EWM.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EWM.Controllers
{
    public class ProductController : Controller
    {
        //? Verify Customer Login status
        public ActionResult CheckCustomerLogin()
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Customer")) { return Json("Please login first!"); }
            return Json("Ok");
        }


        // GET: Product
        public ActionResult ProductAll(string section = "")
        {
            //List<MstProduct> pList = MstProduct.GetAllCompleteProductData("Active");

            MstCategory cat1 = new MstCategory()
            {
                CatLevel = 1
            };
            List<MstCategory> catList = cat1.SelectMstCategory("All");
            ViewData["MaxCat"] = MstCategory.GetMaxCat();
            ViewData["CatList"] = catList;
            TempData["HomeFilter"] = section;
            return View();
        }

        public ActionResult ProductCard_Partial(string selectedCategories = "")
        {
            List<MstProduct> productList = MstProduct.GetAllCompleteProductData("Active");
            string homeFilter = (TempData["HomeFilter"] == null) ? "" : TempData["HomeFilter"].ToString();

            if (!string.IsNullOrEmpty(homeFilter))
            {
                MstCategory cat = new MstCategory()
                {
                    CatLevel = 1,
                    CategoryDesc = TempData["HomeFilter"].ToString()
                };
                List<MstCategory> catList = cat.SelectMstCategory("All");

                if (catList.Count > 0)
                {
                    string[] catArr = { catList[0].CategoryId };
                    productList = MstProduct.GetProductByCategory(catArr);
                }

            }

            if (!string.IsNullOrEmpty(selectedCategories))
            {
                string[] catList = (string[])Newtonsoft.Json.JsonConvert.DeserializeObject(selectedCategories, typeof(string[]));

                productList = MstProduct.GetProductByCategory(catList);
            }

            return PartialView(productList);
        }

        // Product Filters
        public ActionResult ProductFilter_Partial()
        {
            MstCategory cat1 = new MstCategory()
            {
                CatLevel = 1
            };

            List<MstCategory> catList = cat1.SelectMstCategory("All");
            ViewData["MaxCat"] = MstCategory.GetMaxCat();
            return PartialView(catList);
        }

        // Single Product Item display
        public ActionResult ProductSingle(string productId)
        {
            if (string.IsNullOrEmpty(productId))
            {
                return RedirectToAction("ProductAll");
            }

            MstProduct product = MstProduct.GetCompleteProductData(productId, "Active");

            if (GeneralBLL.VerifyAccessRight(Session["AccountType"], "Customer"))
            {
                MstCustomer user = (MstCustomer)Session["Account"];

                // Checking if customer has purchased the product
                bool hasPurchased = TxnOrderHdr.CheckCustomerProductOrders(user.CustomerId, productId);
                ViewData["Purchased"] = hasPurchased;

                // Checking if the customer has reviewed the product
                MstProductReview review = new MstProductReview();
                review.CustomerId = user.CustomerId;
                review.ProductId = productId;

                int hasReview = review.CheckMstProductReview();

                if (hasReview > 0)
                {
                    ViewData["Reviewed"] = true;
                }
                else
                {
                    ViewData["Reviewed"] = false;
                }
            }

            int productReviews = MstProductReview.GetProductReviewsAll(productId).Count;
            ViewData["ReviewCount"] = productReviews;
            return View(product);
        }


        public List<MstProduct> GetProductByCategory(string catId = "")
        {
            List<MstProduct> allProducts = MstProduct.GetAllCompleteProductData("Active");

            allProducts.RemoveAll(i => i.GetCatList().FindIndex(c => c.CategoryId == catId) == -1);
            return allProducts;
        }


        //? AJAX call for Parent Cat dropdown
        public ActionResult GetParentCat_Cb(int catLevel = 1, string parentId = "", string selectedData = "")
        {
            MstCategory catSearch = new MstCategory();
            catSearch.CatLevel = catLevel;
            catSearch.ParentCatId = parentId;
            List<MstCategory> parentList = catSearch.SelectMstCategory("All");
            List<SelectListItem> selectionList = new List<SelectListItem>();

            for (int i = 0; i < parentList.Count; i++)
            {
                MstCategory item = parentList[i];
                SelectListItem selectionItem = new SelectListItem();
                selectionItem.Text = item.CategoryCode;
                selectionItem.Value = item.CategoryId;

                //if (pageMode == "New" && i == 0 && catLevel == 1)
                //{
                //    selectionItem.Selected = true;
                //}

                if (selectedData == item.CategoryId)
                {
                    selectionItem.Selected = true;
                }
                selectionList.Add(selectionItem);
            }

            return Json(selectionList);
        }

        //? AJAX - Add items to shopping cart
        public ActionResult AddToShoppingCart(string productId, string quantity)
        {
            // get item id > update quantity
            // update nav header

            // Validating that customer is logged in
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Customer")) { return Json("Please login first!"); }
            MstCustomer user = (MstCustomer)Session["Account"];

            TxnShoppingCart cart = TxnShoppingCart.GetTxnShoppingCartItems(user.CustomerId);

            TxnShoppingCart cartItem = cart.GetCartItems().Find(l => l.ProductId == productId);

            if (cartItem == null) // if item is not in cart
            {
                cartItem = new TxnShoppingCart();
                cartItem.CustomerId = user.CustomerId;
                cartItem.ProductId = productId;
                cartItem.Quantity = int.Parse(quantity);
                cartItem.CreateTxnShoppingCartItem(user.Username);

            }
            else //if item is already in cart
            {
                cartItem.Quantity = cartItem.Quantity + int.Parse(quantity);
                cartItem.UpdateTxnShoppingCartItem();
            }

            Session["ShoppingCart"] = cart.RetrieveCartItemsFromDb().Count;

            return Json("Ok");
        }

        public ActionResult ProductReview_Partial(string productId, string readonlyReview = "")
        {
            MstCustomer member = new MstCustomer();
            member.CustomerId = "-1";
            if (GeneralBLL.VerifyAccessRight(Session["AccountType"], "Customer"))
            {
                member = (MstCustomer)Session["Account"];
            }

            MstProductReview customerReview = MstProductReview.GetCustomerReview(productId, member.CustomerId);
            ViewData["ProductId"] = productId;
            ViewData["Readonly"] = readonlyReview;
            return PartialView(customerReview);
        }

        public ActionResult ProductReviewAll_PopupPartial(string productId)
        {
            MstCustomer member = new MstCustomer();
            if (GeneralBLL.VerifyAccessRight(Session["AccountType"], "Customer"))
            {
                member = (MstCustomer)Session["Account"];
            }
            List<MstProductReview> reviewList = MstProductReview.GetProductReviewsAll(productId);

            return PartialView(reviewList);
        }

        public ActionResult ProductReviewCustomer_Card(string productId, string displayLocation = "")
        {
            MstCustomer member = new MstCustomer();
            if (GeneralBLL.VerifyAccessRight(Session["AccountType"], "Customer"))
            {
                member = (MstCustomer)Session["Account"];
            }

            MstProductReview customerReview = MstProductReview.GetCustomerReview(productId, member.CustomerId);
            ViewData["Display"] = displayLocation;
            return PartialView("ProductReviewCard_Partial", customerReview);
        }

        public ActionResult ProductReviewSummary_Partial(string productId, decimal rating = 0)
        {
            System.Data.DataTable dt = MstProductReview.CountProductRatingSummary(productId);
            Dictionary<int, int> reviewSummary = new Dictionary<int, int>();


            int rowIndex = 0;
            if (dt.Rows.Count > 0)
            {
                for (int i = 1; i <= 5; i++)
                {
                    if (rowIndex < dt.Rows.Count)
                    {

                        decimal rowValue = Decimal.Parse(dt.Rows[rowIndex][0].ToString());

                        if ((int)rowValue == i)
                        {
                            reviewSummary.Add(i, int.Parse(dt.Rows[rowIndex][1].ToString()));
                            rowIndex++;
                        }
                        else
                        {
                            reviewSummary.Add(i, 0);
                        }
                    }
                    else
                    {
                        reviewSummary.Add(i, 0);
                    }
                }
            }
            else
            {
                for (int i = 1; i <= 5; i++)
                {
                    reviewSummary.Add(i, 0);
                }
            }

WetMarketOnline/Views/Shared/_Layout.cshtml
@using EWM.Models
@{
    string accountType = (Session["AccountType"] == null) ? "" : Session["AccountType"].ToString();
    //  int cartNumber = (Session["ShoppingCart"] == null) ? 0 : int.Parse(Session["ShoppingCart"].ToString());
    string accObjType = "Mst" + accountType;
    string userHome = (accountType == "Admin" || accountType == "Merchant") ? "Manage" : "Profile";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>EWM - @ViewBag.Title </title>
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    @*@Scripts.Render("~/bundles/modernizr")
        @Styles.Render("~/Content/css")*@
    <link rel="shortcut icon" type="image/ico" href="@Url.Content("~/ewm.ico")">
    @Scripts.Render("~/bundles/bootstrap")
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    @*<link rel="stylesheet" href="~/Content/bootstrap.min.css" />*@

    @*<link rel="stylesheet" href="~/Content/ewm-stylesheet.css" />*@
</head>

<body id="ewmNavbar" class="d-flex flex-column min-vh-100">
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                <img src="~/Content/Img/ewm_logo.png" alt="E-WM" height="30" class="d-inline-block align-text-top">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarUserOptions" aria-controls="navbarUserOptions" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarUserOptions">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0 me-2">
                    @{

                        if (accountType == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("ManageHomeSlider", "MstHomeSlider")">Manage Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("ManagePromotion", "MstPromotion")">Manage Promotion</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("ManageCategory", "MstCategory")">Manage Categories</a>
                            </li>
                        }
                        else if (accountType == "Merchant")
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("ManageProduct", "MstMerchant")">Manage Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("OrderList_Merchant", "MstMerchant")">View Orders</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Home")">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("About", "Home")">About Us</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("ProductAll", "Product")">Product</a>
                            </li>
                        }
                    }
                    @{

                        if (!string.IsNullOrEmpty(accountType))
                        {
                            <li class="nav-item dropdown dropstart">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-person-circle"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdownMenuLink">
                                    <li class="dropdown-item"><a class="nav-link" href="@Url.Action(accObjType, accObjType)">@userHome</a></li>
                                    @{
                                        if (accountType == "Admin")
                                        {
                                            <li class="dropdown-item"><a class="nav-link" href="@Url.Action("OrderList_Admin", "MstAdmin")">View Orders</a></li>
                                        }
                                        if (accountType == "Merchant")
                                        {
                                            <li class="dropdown-item"><a class="nav-link" href="@Url.Action("OrderList_Merchant", "MstMerchant")">View Orders</a></li>
                                        }
                                        if (accountType == "Customer")
                                        {
                                            <li class="dropdown-item"><a class="nav-link" href="@Url.Action("OrderList", "MstCustomer")">View Orders</a></li>
                                        }
                                    }
                                    <li class="dropdown-item"><a class="nav-link" href="@Url.Action("Logout", "Account")">Logout</a></li>
                                </ul>
                            </li>
                            if (accountType == "Customer")
                            {
                                <li id="navCart" class="nav-item">
                                    @Html.Partial("_LayoutCart")
                                </li>
                            }
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Login", "Account")">Login</a>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </nav>
    <br /><br />
    <div class="container body-content">
        @RenderBody()
        @*<hr />*@
    </div>


    <footer class="bd-footer bg-dark text-center text-white py-5 mt-auto">
        @*              <footer class="bg-dark text-center text-white">*@
        @*<nav class="navbar fixed-bottom navbar-dark bg-dark text-center text-white">*@
        <!-- Grid container -->
        <div class="container mt-4 justify-content-center">
            <!-- Section: Social media -->
            <section class="mb-4">
                <!-- Facebook -->

                <a class="btn btn-outline-light btn-floating m-1" href="https://www.facebook.com/" role="button">
                    <i class="bi bi-facebook"></i>
                </a>

                <!-- Twitter -->
                <a class="btn btn-outline-light btn-floating m-1" href="https://twitter.com/i/flow/login" role="button">
                    <i class="bi bi-twitter"></i>
                </a>

                <!-- Instagram -->
                <a class="btn btn-outline-light btn-floating m-1" href="https://www.instagram.com/?hl=en" role="button">
                    <i class="bi bi-instagram"></i>
                </a>

                <!-- Linkedin -->
                <a class="btn btn-outline-light btn-floating m-1" href="https://www.linkedin.com/" role="button">
                    <i class="bi bi-linkedin"></i>
                </a>
            </section>
            <!-- Section: Social media -->
        </div>

        <!-- Copyright -->
        <div class="text-center" style="width:100%;">
            © 2022 Copyright: E-WM
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.css" />
    @*@Scripts.Render("~/bundles/bootstrap")
        @Styles.Render("~/Content/css")
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">*@
    @RenderSection("scripts", required: false)
</body>
</html>

WetMarketOnline/Views/Shared/_LayoutCart.cshtml
@{
    int cartNumber = (Session["ShoppingCart"] == null) ? 0 : int.Parse(Session["ShoppingCart"].ToString());
}
    <a class="nav-link" href="@Url.Action("ShoppingCart", "ShoppingCart")">
        <i class="bi bi-cart4 position-relative">
            @{
                if (cartNumber > 0)
                {
                    <span class="position-absolute top-0 start-100 translate-middle badge rounded-circle bg-danger" style="font-size:10px">
                        @cartNumber
                        <span class="visually-hidden">Items in Cart</span>
                    </span>
                }
            }
        </i>
    </a>