WetMarketOnline/Models/MstMerchant.cs
using EWM.HelperClass;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace EWM.Models
{
    public class MstMerchant
    {
        private static log4net.ILog Log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        public static string ObjectName = typeof(MstMerchant).AssemblyQualifiedName;
        public static string ListName = typeof(List<MstMerchant>).AssemblyQualifiedName;

        public string MerchantId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }

       
        // Original Data
        private string OriMerchantId { get; set; }
        private string OriUsername { get; set; }
        private string OriPassword { get; set; }
        private string OriName { get; set; }
        private string OriEmail { get; set; }
        private string OriAddress { get; set; }
        private string OriState { get; set; }
        private string OriPostcode { get; set; }
        private string OriStatus { get; set; }
        private DateTime OriCreatedDate { get; set; }
        private string OriCreatedBy { get; set; }
        private DateTime OriUpdatedDate { get; set; }
        private string OriUpdatedBy { get; set; }

        // Default Constructor
        public MstMerchant() { }

        // Constructor - Retrieve from Db based on PK
        public static MstMerchant GetMstMerchant(string merchantId)
        {
            MstMerchant merchant = new MstMerchant();
            merchant.MerchantId = merchantId;

            SqlCommand cmd = DatabaseManager.ConstructSqlCommand(ObjectName, merchant, filterType: "All");
            List<MstMerchant> merchantList = (List<MstMerchant>)DatabaseManager.ExecuteQueryCommand_Object(cmd, ObjectName, ListName);

            if (merchantList.Count == 1)
            {
                return merchantList[0];
            }
            return null;
        }

        #region Methods

        //? Insert new record
        public int CreateMstMerchant(string userName = "")
        {
            this.MerchantId = Guid.NewGuid().ToString();
            this.Status = "Active";
            this.CreatedDate = DateTime.Now;
            this.UpdatedDate = DateTime.Now;
            this.CreatedBy = userName;
            this.UpdatedBy = userName;

            SqlCommand cmd = DatabaseManager.ConstructSqlCommand(ObjectName, this, "Insert");
            int rowsAffected = DatabaseManager.ExecuteQueryCommand_RowsAffected(cmd);

            return rowsAffected;
        }

        //? Update existing record
        public int UpdateMstMerchant(string userName = "")
        {
            this.UpdatedDate = DateTime.Now;
            this.UpdatedBy = userName;

            SqlCommand cmd = DatabaseManager.ConstructSqlCommand(ObjectName, this, "Update");
            int rowsAffected = DatabaseManager.ExecuteQueryCommand_RowsAffected(cmd);

            return rowsAffected;
        }

        //? Delete existing record
        public int DeleteMstMerchant()
        {
            SqlCommand cmd = DatabaseManager.ConstructSqlCommand(ObjectName, this, "Delete");
            int rowsAffected = DatabaseManager.ExecuteQueryCommand_RowsAffected(cmd);

            return rowsAffected;
        }

        //? Insert new record
        public List<MstMerchant> SelectMstMerchant(string filterType = "Column")
        {
            SqlCommand cmd = DatabaseManager.ConstructSqlCommand(ObjectName, this, "Select", filterType);
            List<MstMerchant> data = (List<MstMerchant>)DatabaseManager.ExecuteQueryCommand_Object(cmd, ObjectName, ListName);

            return data;
        }

        //? Runs a Select statement and returns the number of rows found
        public int CheckMstMerchant()
        {
            SqlCommand cmd = DatabaseManager.ConstructSqlCommand(ObjectName, this, "Select", filterType: "All");
            int data = DatabaseManager.ExecuteQueryCommand_RowsAffected(cmd, true);

            return data;
        }
        #endregion


    }
}

WetMarketOnline/Controllers/MstMerchantController.cs
using EWM.HelperClass;
using EWM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EWM.Controllers
{
    public class MstMerchantController : Controller
    {
        private static log4net.ILog Log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        // GET: MstMerchant
        public ActionResult MstMerchant()
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Merchant")) { return RedirectToAction("Login", "Account"); }

            ViewBag.Message = "Placeholder Merchant Page";
            return View();
        }



        //? MstMerchant Manage Product Page
        public ActionResult ManageProduct()
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Merchant")) { return RedirectToAction("Login", "Account"); }
            MstMerchant user = (MstMerchant)Session["Account"];

            MstProduct productSearch = new MstProduct();
            productSearch.MerchantId = user.MerchantId;
            List<MstProduct> list = productSearch.SelectMstProduct("All");

            ViewData["MaxCat"] = MstCategory.GetMaxCat();
            ViewBag.Error = TempData["Error"];
            return View(list);
        }

        // GET: MstProduct/Details/5
        public ActionResult ProductDetails(string id, string mode, int productLevel = 1)
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Merchant")) { return RedirectToAction("Login", "Account"); }
            MstProduct productSearch = new MstProduct();
            //productSearch.CatLevel = productLevel - 1;
            //List<MstProduct> parentList = productSearch.SelectMstProduct("All");
            //List<SelectListItem> selectionList = new List<SelectListItem>();

            //foreach (var item in parentList)
            //{
            //    SelectListItem selectionItem = new SelectListItem();
            //    selectionItem.Text = item.ProductCode;
            //    selectionItem.Value = item.ProductId;
            //    selectionList.Add(selectionItem);
            //}

            //ViewData["ParentList"] = selectionList;
            ViewData["MaxCat"] = MstCategory.GetMaxCat();
            ViewData["PageMode"] = mode;

            if (mode == "New")
            {
                return View("MstProduct_Details", new MstProduct() { ProductId = Guid.NewGuid().ToString() });
            }
            else
            {
                MstProduct productData = MstProduct.GetCompleteProductData(id);

                //if (productLevel > 1)
                //{
                //    MstProduct parent = MstProduct.GetMstProduct(productData.ParentCatId);
                //    productData.ParentCatId = parent.ProductCode;
                //}
                return View("MstProduct_Details", productData);
            }
        }

        [HttpPost]
        public ActionResult UpdateMstProduct(MstProduct formData, string mode, FormCollection MstProductForm = null, int maxCat = 1)
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Merchant")) { return RedirectToAction("Login", "Account"); }
            MstMerchant member = (MstMerchant)Session["Account"];
            List<MstProductCategory> formCategoryList = new List<MstProductCategory>();
            int rowsAffected = -1;

            for (int i = 1; i <= maxCat; i++)
            {
                string category = MstProductForm.Get("Cat" + i);
                if (!string.IsNullOrEmpty(category))
                {
                    MstProductCategory cat = new MstProductCategory();
                    cat.ProductId = formData.ProductId;
                    cat.CatId = category;
                    formCategoryList.Add(cat);
                }
            }

            if (mode == "New")
            {
                rowsAffected = formData.CreateMstProduct(member.Username);

                //Add product category
                foreach (var item in formCategoryList)
                {
                    item.CreateMstProductCategory(member.Username);
                }

            }
            else if (mode == "Edit")
            {
                // Delete existing product category data
                MstProductCategory existingCat = new MstProductCategory();
                existingCat.ProductId = formData.ProductId;
                List<MstProductCategory> pCatList = existingCat.SelectMstProductCategory("All");
                foreach (var item in pCatList)
                {
                    item.DeleteMstProductCategory();
                }


                // Update Mst Product
                MstProduct oriData = MstProduct.GetMstProduct(formData.ProductId);
                oriData.ProductCode = formData.ProductCode;
                oriData.ProductName = formData.ProductName;
                oriData.ProductDesc = formData.ProductDesc;
                oriData.Price = formData.Price;
                oriData.Quantity = formData.Quantity;
                oriData.Status = formData.Status;

                rowsAffected = oriData.UpdateMstProduct(member.Username);

                //Add product category
                foreach (var item in formCategoryList)
                {
                    item.CreateMstProductCategory(member.Username);
                }
            }



            if (rowsAffected == 1)
            {
                return RedirectToAction("ManageProduct");
            }
            else
            {
                ViewBag.Error = "Error processing request. Please try again";
                ViewData["PageMode"] = mode;
                return View("MstProduct_Details", formData);
            }

        }

        /// GET: MstProduct/Delete/5
        public ActionResult DeleteProduct(string id)
        {
            MstProduct deleteCat = MstProduct.GetCompleteProductData(id);

            int rowsAffected = deleteCat.DeleteMstProduct();

            foreach (var item in deleteCat.GetCatList())
            {
                item.DeleteMstCategory();
            }

            foreach (var item in deleteCat.GetImageList())
            {
                item.DeleteMstProductImage();
            }

            if (rowsAffected != 1)
            {
                TempData["Error"] = "Failed to delete the product. Please try again.";
            }
            return RedirectToAction("ManageProduct");
        }

        public ActionResult ProductImage_Partial(string productId, List<MstProductImage> imgList = null, string pageMode = "")
        {


            if (imgList == null || imgList.Count == 0)
            {
                MstProductImage search = new MstProductImage() { ProductId = productId };
                imgList = search.SelectMstProductImage("All");
            }

            ViewData["PageMode"] = pageMode;
            return PartialView(imgList);
        }

        //? AJAX call for Parent Cat dropdown
        public ActionResult GetParentCat_Cb(int catLevel = 1, string parentId = "", string pageMode = "", string selectedData = "")
        {
            MstCategory catSearch = new MstCategory();
            catSearch.CatLevel = catLevel;
            catSearch.ParentCatId = parentId;
            List<MstCategory> parentList = catSearch.SelectMstCategory("All");
            List<SelectListItem> selectionList = new List<SelectListItem>();

            for (int i = 0; i < parentList.Count; i++)
            {
                MstCategory item = parentList[i];
                SelectListItem selectionItem = new SelectListItem();
                selectionItem.Text = item.CategoryCode;
                selectionItem.Value = item.CategoryId;

                if (pageMode == "New" && i == 0 && catLevel == 1)
                {
                    selectionItem.Selected = true;
                }

                if (selectedData == item.CategoryId)
                {
                    selectionItem.Selected = true;
                }
                selectionList.Add(selectionItem);
            }

            return Json(selectionList);
        }

        public ActionResult ProductImage_PopupPartial(string productId = "", string productImageId = "")
        {
            MstProductImage img = (string.IsNullOrEmpty(productImageId)) ? new MstProductImage() { ProductId = productId } : MstProductImage.GetMstProductImage(productImageId);            
            string jsonImg = Newtonsoft.Json.JsonConvert.SerializeObject(img);
            return Content(jsonImg);
        }

        [HttpPost]
        public ActionResult SaveMstProductImage(MstProductImage popupImage = null, HttpPostedFileBase ProductImageUpload = null, FormCollection MstProductImageForm = null)
        {
            if (!GeneralBLL.VerifyAccessRight(Session["AccountType"], "Merchant")) { return RedirectToAction("Login", "Account"); }
            MstMerchant member = (MstMerchant)Session["Account"];
            string fileExtension = "";
            string filePath = "";
            int rowsAffected = -1;
            string mode = MstProductImageForm.Get("Mode_Img");

            //Get absolute Upload path 
            string UploadPath = Server.MapPath(GeneralBLL.FileDirectory);

            popupImage.ProductId = MstProductImageForm.Get("ProductId_Img");
            popupImage.Status = MstProductImageForm.Get("Status_Img");

            // File Path Configuration
            if (ProductImageUpload != null)
            {
                string fileName = MstProductImageForm.Get("Filename");
                fileExtension = System.IO.Path.GetExtension(ProductImageUpload.FileName);

                //Add Current Date To Attached File Name : Filename_20220226.png
                string completeFileName = fileName.Trim() + "_" + DateTime.Now.ToString("yyyyMMdd") + fileExtension;

                //Create relative path to store in server.  

WetMarketOnline/Views/MstMerchant/ManageProduct.cshtml
@using EWM.Models;
@model IEnumerable<EWM.Models.MstProduct>

@{
    ViewBag.Title = "ManageProducts";
}

<h2>Manage Products</h2>


<div class="table-responsive">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MerchantId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UpdatedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UpdatedBy)
            </th>
            <th colspan="3" class="text-center">@Html.ActionLink("Add New", "ProductDetails", new { mode = "New" })</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @{
                        MstMerchant merchant = MstMerchant.GetMstMerchant(item.MerchantId);
                    }                       
                        @merchant.Name
                    @Html.DisplayText(merchant.Name)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UpdatedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UpdatedBy)
                </td>
                <td>
                    @Html.ActionLink("Edit", "ProductDetails", new { id = item.ProductId, mode = "Edit" }) |
                    @Html.ActionLink("Details", "ProductDetails", new { id = item.ProductId, mode = "Details" }) |
                    @Html.ActionLink("Delete", "DeleteProduct", new { id = item.ProductId }, new { onclick = "return confirm('Are you sure you wish to delete item: " + item.ProductName + "?');" })
                </td>
            </tr>
        }

    </table>
</div>

WetMarketOnline/Views/MstMerchant/MstMerchant.cshtml
@{
    ViewBag.Title = "Merchant Home";
}
@*<a href='@Url.Action("ManageProduct", "MstMerchant")'>Manage Products</a>*@
<div class="row row-cols-3 my-5 justify-content-center text-center">
    <div class="col card text-black me-3" style="max-width: 250px;">
        <a class="custom-link" href='@Url.Action("ManageProduct", "MstMerchant")'>
            @*<img src="~/Content/Img/Admin_ManageHome.png" class="card-img" alt="Manage Products Icon">*@
            <i class="bi bi-shop" style="font-size: 8rem; color: black;"></i>
            <div class="card-body">
                <h5 class="card-title">Manage Products</h5>
            </div>
        </a>
    </div>

    <div class=" col card text-black me-3" style="max-width: 250px;">
        <a class="custom-link" href='@Url.Action("OrderList_Merchant")'>
            @*<img src="~/Content/Img/Admin_ManageHome.png" class="card-img" alt="Manage Products Icon">*@
            <i class="bi bi-bag-fill" style="font-size: 8rem; color: black;"></i>
            <div class="card-body">
                <h5 class="card-title">View Orders</h5>
            </div>
        </a>
    </div>
</div>

WetMarketOnline/Views/MstMerchant/OrderCard_MerchantPartial.cshtml
@using EWM.Models;
@model List<TxnOrderHdr>
@{
    if(Model.Count == 0)
    {
        <h4><strong>No orders.</strong></h4>
    }

    foreach (var item in Model)
    {
        string iconClass = (item.Status == "Delivered") ? "bi-box2" : (item.Status == "Picked Up") ? "bi-person-fill" : (item.Status == "On the Way") ? "bi-truck" : "bi-check-lg";
        decimal price = Math.Round(item.TotalPrice.Value, 2);

        <a href='@Url.Action("OrderTracking_Merchant", new { orderHdrId = item.OrderHdrId})' class="text-decoration-none text-reset">
            <div class="card mb-4">
                <div class="card-header bg-secondary bg-gradient text-white">
                    Order Id: #@item.OrderHdrId
                </div>
                <div class="row g-0">
                    <div class="col-md-3 justify-content-center text-center m-auto">
                        <span class="px-3 border border-1 border-dark rounded-3" style="font-size:5rem;">
                            <i class="bi @iconClass"></i>
                        </span>
                    </div>
                    <div class="col-md-9">
                        <div class="card-body">
                            <h5 class="card-title">Order Date: @item.OrderDate.ToString("dd-MM-yyyy")</h5>
                            <p class="card-text">Status: @item.Status</p>
                            <p class="card-text">Total: RM @price</p>
                            <p class="card-text"><small class="text-muted">@item.GetOrderDetails().Count item(s)</small></p>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    }
}

WetMarketOnline/Views/MstMerchant/OrderList_Merchant.cshtml
@{
    ViewBag.Title = "Order List";
}

<script type="text/javascript">
    $(document).ready(() => {
        $("#orderFilter").change(e => {
            filterOrders();
        })
    });

    function filterOrders() {
        var orderStatus = $("#orderFilter").val();

         $.ajax({
                type: "POST",
                url: '@Url.Action("OrderCard_MerchantPartial")',
                data: {
                    status: orderStatus
                },
                dataType: "html",
             success: function (result) {
                 $("#OrderCard_Partial").html(result);                 
                }
            });
    }
</script>

<h2>Orders</h2>
<hr />
@* Filter *@
<div class="mb-5">

<h6 class="title">Filter Order Status:</h6>
<select id="orderFilter" class="form-select" aria-label="Select an order filter">
    <option selected>All</option>
    <option value="Order Confirmed">Order Confirmed</option>
    <option value="Picked Up">Picked Up</option>
    <option value="On the Way">On the Way</option>
    <option value="Delivered">Delivered</option>
</select>
</div>

@* Order List *@
<div id="OrderCard_Partial">
    @{Html.RenderAction("OrderCard_MerchantPartial");    }
</div>

WetMarketOnline/Views/MstMerchant/OrderTracking_Merchant.cshtml
@using EWM.Models;
@model TxnOrderHdr

@{
    ViewBag.Title = "Order Tracking";

    string directory = EWM.HelperClass.GeneralBLL.FileDirectory;

    string confirmStatus = "active";
    string pickUpStatus = "";
    string shippingStatus = "";
    string deliveryStatus = "";

    if (Model.Status == "Picked Up")
    {
        pickUpStatus = "active";
    }

    if (Model.Status == "On the Way")
    {
        pickUpStatus = "active";
        shippingStatus = "active";
    }

    if (Model.Status == "Delivered")
    {
        pickUpStatus = "active";
        shippingStatus = "active";
        deliveryStatus = "active";
    }
    //alter table txn_order_hdr alter column status varchar(100)

} 

@*<h2>OrderTracking</h2>*@

<div class="container mb-4">
    <article class="card">
        <div class="card-body">
            <h6>Order ID: #@Model.OrderHdrId</h6>
            <article class="card">
                <div class="card-body row">
                    @*<div class="col"><strong>Estimated Delivery time:</strong> <br>29 nov 2019 </div>*@
                    <div class="col"> <strong>Shipping By:</strong> <br> EWM Courier | <i class="bi bi-phone"></i> +60-123 5134 </div>
                    <div class="col"> <strong>Status:</strong> <br> @Model.Status</div>
                    @*<div class="col"> <strong>Tracking #:</strong> <br> BD045903594059 </div>*@
                </div>
            </article>
            <hr />
            <div class="track">
                <div class="step @confirmStatus"> <span class="icon"> <i class="bi bi-check-lg"></i></span> <span class="text">Order confirmed</span> </div>
                <div class="step @pickUpStatus"> <span class="icon"> <i class="bi bi-person-fill"></i> </span> <span class="text"> Picked by courier</span> </div>
                <div class="step @shippingStatus"> <span class="icon"> <i class="bi bi-truck"></i> </span> <span class="text"> On the way </span> </div>
                <div class="step @deliveryStatus"> <span class="icon"> <i class="bi bi-box2-fill"></i> </span> <span class="text">Delivered</span> </div>
            </div>
            <hr />
            <ul class="track-item row">
                @{
                    foreach (var item in Model.GetOrderDetails())
                    {
                        MstProduct orderItem = item.GetOrderItem();
                        MstProductImage img = (orderItem.GetImageList().Count <= 0) ? null : orderItem.GetImageList().OrderBy(l => l.ImageOrder).ToList()[0];
                        string imgLink = (img != null) ? String.Concat(directory, img.FileLocation) : "";
                        string desc = (img != null) ? img.ImageDesc : "Image not found";
                        decimal price = Decimal.Round(orderItem.Price.Value, 2);

                        <li class="col-md-4">
                            <figure class="itemside mb-3">
                                <div class="aside"><img src="@imgLink" alt="@desc" class="img-sm border"></div>
                                <figcaption class="info align-self-center">
                                    <p class="title">@orderItem.ProductName</p>
                                    <p class="title text-muted">RM @price | @item.Quantity unit(s)</p>
                                    <small class="text-muted">@orderItem.GetMerchantName()</small>
                                </figcaption>
                            </figure>
                        </li>
                    }
                }
            </ul>
            @*<hr>
            <div class="card-body row">
                <div class="col"> <strong>Shipping Fee:</strong> <br> RM 5.00</div>
                <div class="col"> <strong>Promotion:</strong> <br> @Model.GetPromotionCode() | RM @Math.Round(Model.Discount.Value, 2) </div>
                <div class="col"> <strong>Order Total:</strong> <br> RM @Math.Round(Model.TotalPrice.Value, 2)</div>                
            </div>*@
            <hr>
            <a href='@Url.Action("OrderList_Merchant")' class="btn btn-warning mt-5" data-abc="true"> <i class="bi bi-chevron-left"></i> Back to orders</a>
        </div>
    </article>
</div>

WetMarketOnline/Views/MstMerchant/ProductImage_PopupPartial.cshtml
@model EWM.Models.MstProductImage

@{
    //string mode = (ViewData["PopupMode"] == null) ? "" : ViewData["PopupMode"].ToString();
}

<!-- Modal -->
<div class="modal fade" id="productImagePopup" tabindex="-1" aria-labelledby="productImagePopupLabel" aria-hidiven="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="productImagePopupLabel">Product Image</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            @using (Html.BeginForm("SaveMstProductImage", "MstMerchant", FormMethod.Post, new { enctype = "multipart/form-data", @id = "MstProductImageForm" }))
            {
                <div class="modal-body">
                    @Html.TextBoxFor(model => model.ProductImageId, new { @class = "visually-hidden" })
                    @Html.TextBox("ProductId_Img", "", new { @class = "visually-hidden" })
                    @Html.TextBox("Mode_Img", "", new { @class = "visually-hidden" })
                    <div>
                        @Html.DisplayNameFor(model => model.Filename)
                    </div>

                    <div class="mb-4">
                        @Html.TextBoxFor(model => model.Filename, new { @class = "form-control" })
                    </div>

                    <div>
                        @Html.DisplayNameFor(model => model.ImageDesc)
                    </div>

                    <div class="mb-4">
                        @Html.TextBoxFor(model => model.ImageDesc, new { @class = "form-control" })
                    </div>

                    <div>
                        @Html.DisplayNameFor(model => model.FileLocation)
                    </div>

                    <div class="mb-4 text-break">
                        @Html.TextBoxFor(model => model.FileLocation, new { @readonly = "true", @class = "form-control" })
                        <div class="row-cols-sm-3 row-cols-lg-6 mt-sm-3">
                            <button id="btnFile" type="button" class="btn btn-primary end-0" onclick="OpenFileDialog()">Upload File</button>
                            <input class="form-control visually-hidden" type="file" id="ProductImageUpload" name="ProductImageUpload" onchange="IndicateFileUpload()">

                        </div>
                    </div>

                    <div>
                        @Html.DisplayNameFor(model => model.ImageOrder)
                    </div>

                    <div class="mb-4">
                        @Html.TextBoxFor(model => model.ImageOrder, new { @class = "form-control", @type = "number", @step = "1", @min = "1", @required = "true" })
                    </div>


                    <div>
                        @Html.DisplayNameFor(model => model.ExtensionType)
                    </div>

                    <div class="mb-4">
                        @Html.TextBoxFor(model => model.ExtensionType, new { @class = "form-control border-0 bg-transparent", @readonly = "true" })
                    </div>

                    <div>
                        @Html.DisplayNameFor(model => model.Status)
                    </div>

                    <div class="mb-4">
                        @Html.DropDownList("Status_Img", EWM.HelperClass.GeneralBLL.GetStatusDropdownItems(), new { @class = "form-select" })

                    </div>

                    <div>
                        @Html.DisplayNameFor(model => model.UpdatedDate)
                    </div>

                    <div class="mb-4">
                        @Html.TextBoxFor(model => model.UpdatedDate, new { @class = "form-control border-0 bg-transparent", @readonly = "true" })
                    </div>

                    <div>
                        @Html.DisplayNameFor(model => model.UpdatedBy)
                    </div>

                    <div class="mb-4">
                        @Html.TextBoxFor(model => model.UpdatedBy, new { @class = "form-control border-0 bg-transparent", @readonly = "true" })
                    </div>
                </div>
                <div class="modal-footer ">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal" onclick="DeleteProductImage()">Delete</button>

                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Back</button>
                    <button type="button" class="btn btn-primary" onclick="SubmitProductImage()" data-bs-dismiss="modal">Submit</button>
                </div>
            }
        </div>
    </div>
</div>